name: Pypendency

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
    name: Pypendency tests on ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - name: Build Docker image
        run: |
          docker build . -t pypendency-dev:python-${{ matrix.python-version }} --build-arg PYTHON_VERSION=${{ matrix.python-version }}
      - name: Unittest
        run: |
          docker run -v $(pwd)/.:/usr/src/app pypendency-dev:python-${{ matrix.python-version }} bash -c "pipenv run make run-tests"
