name: Pypendency

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
    name: Pypendency tests on ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Unittest
        env:
          PYTHONPATH: ${PYTHONPATH}:${PWD}:src/
        run: |
          pipenv run make run-tests
